# Generated by Django 3.2.23 on 2024-01-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notes_quanity',
            field=models.IntegerField(default=0),
        ),
    ]
